---
ms.date: 09/13/2016
ms.topic: reference
title: Прерывающие ошибки
description: Прерывающие ошибки
ms.openlocfilehash: b7c9b949a654f10a0421ea69dfe955c8dfb5627e
ms.sourcegitcommit: ba7315a496986451cfc1296b659d73ea2373d3f0
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 12/10/2020
ms.locfileid: "92652553"
---
# <a name="terminating-errors"></a><span data-ttu-id="d1f9c-103">Прерывающие ошибки</span><span class="sxs-lookup"><span data-stu-id="d1f9c-103">Terminating Errors</span></span>

<span data-ttu-id="d1f9c-104">В этом разделе обсуждается метод, используемый для сообщения о прекращении ошибок.</span><span class="sxs-lookup"><span data-stu-id="d1f9c-104">This topic discusses the method used to report terminating errors.</span></span> <span data-ttu-id="d1f9c-105">В нем также обсуждается вызов метода из командлета и обсуждаются исключения, которые могут возвращаться средой выполнения Windows PowerShell при вызове метода.</span><span class="sxs-lookup"><span data-stu-id="d1f9c-105">It also discusses how to call the method from within the cmdlet, and it discusses the exceptions that can be returned by the Windows PowerShell runtime when the method is called.</span></span>

<span data-ttu-id="d1f9c-106">При возникновении завершающей ошибки командлет должен сообщить об ошибке, вызвав метод [System. Management. Automation. командлет. ThrowTerminatingError \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) .</span><span class="sxs-lookup"><span data-stu-id="d1f9c-106">When a terminating error occurs, the cmdlet should report the error by calling the [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) method.</span></span> <span data-ttu-id="d1f9c-107">Этот метод позволяет командлету отправить запись об ошибке, описывающую условие, вызвавшее завершающую ошибку.</span><span class="sxs-lookup"><span data-stu-id="d1f9c-107">This method allows the cmdlet to send an error record that describes the condition that caused the terminating error.</span></span> <span data-ttu-id="d1f9c-108">Дополнительные сведения о записях об ошибках см. в статье [записи об ошибках Windows PowerShell](./windows-powershell-error-records.md).</span><span class="sxs-lookup"><span data-stu-id="d1f9c-108">For more information about error records, see [Windows PowerShell Error Records](./windows-powershell-error-records.md).</span></span>

<span data-ttu-id="d1f9c-109">При вызове метода [System. Management. Automation. командлет. ThrowTerminatingError \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) среда выполнения Windows PowerShell безвозвратно останавливает выполнение конвейера и создает исключение [System. Management. Automation. пипелинестоппедексцептион](/dotnet/api/System.Management.Automation.PipelineStoppedException) .</span><span class="sxs-lookup"><span data-stu-id="d1f9c-109">When the [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) method is called, the  Windows PowerShell runtime permanently stops the execution of the pipeline and throws a [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception.</span></span> <span data-ttu-id="d1f9c-110">При последующих попытках вызова метода [System. Management. Automation. командлет. WriteObject](/dotnet/api/System.Management.Automation.Cmdlet.WriteObject), [System. Management. Automation. командлет. WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError)или нескольких других API эти вызовы вызывают исключение [System. Management. Automation. пипелинестоппедексцептион](/dotnet/api/System.Management.Automation.PipelineStoppedException) .</span><span class="sxs-lookup"><span data-stu-id="d1f9c-110">Any subsequent attempts to call [System.Management.Automation.Cmdlet.WriteObject](/dotnet/api/System.Management.Automation.Cmdlet.WriteObject), [System.Management.Automation.Cmdlet.WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError), or several other APIs causes those calls to throw a [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception.</span></span>

<span data-ttu-id="d1f9c-111">Исключение [System. Management. Automation. пипелинестоппедексцептион](/dotnet/api/System.Management.Automation.PipelineStoppedException) также может возникать, если другой командлет в конвейере сообщает об завершающей ошибке, если пользователь попросил остановить конвейер, или если конвейер был остановлен до завершения по какой-либо причине.</span><span class="sxs-lookup"><span data-stu-id="d1f9c-111">The [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception can also occur if another cmdlet in the pipeline reports a terminating error, if the user has asked to stop the pipeline, or if the pipeline has been halted before completion for any reason.</span></span> <span data-ttu-id="d1f9c-112">Командлету не требуется перехватывать исключение [System. Management. Automation. пипелинестоппедексцептион](/dotnet/api/System.Management.Automation.PipelineStoppedException) , если оно не должно очищать открытые ресурсы или его внутреннее состояние.</span><span class="sxs-lookup"><span data-stu-id="d1f9c-112">The cmdlet does not need to catch the [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception unless it must clean up open resources or its internal state.</span></span>

<span data-ttu-id="d1f9c-113">Командлеты могут записывать любое количество выходных объектов или неустранимых ошибок, прежде чем сообщать об завершающей ошибке.</span><span class="sxs-lookup"><span data-stu-id="d1f9c-113">Cmdlets can write any number of output objects or non-terminating errors before reporting a terminating error.</span></span> <span data-ttu-id="d1f9c-114">Тем не менее, завершающая ошибка окончательно останавливает конвейер, а дальнейшие выходные данные, завершающие ошибки или неустранимые ошибки могут быть переданы.</span><span class="sxs-lookup"><span data-stu-id="d1f9c-114">However, the terminating error permanently stops the pipeline, and no further output, terminating errors, or non-terminating errors can be reported.</span></span>

<span data-ttu-id="d1f9c-115">Командлеты могут вызывать [System. Management. Automation. командлет. ThrowTerminatingError \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) только из потока, который вызвал метод обработки входных данных [System. Management. Automation. командлет. BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing), [System.](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord)Management. Automation. командлет. ProcessRecord или [System. Management. Automation. командлет. EndProcessing](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) .</span><span class="sxs-lookup"><span data-stu-id="d1f9c-115">Cmdlets can call [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) only from the thread that called the [System.Management.Automation.Cmdlet.BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing), [System.Management.Automation.Cmdlet.ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord), or [System.Management.Automation.Cmdlet.EndProcessing](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) input processing method.</span></span> <span data-ttu-id="d1f9c-116">Не пытайтесь вызвать [System. Management. Automation. командлет. ThrowTerminatingError \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) или [System. Management. Automation. командлет. WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError) из другого потока.</span><span class="sxs-lookup"><span data-stu-id="d1f9c-116">Do not attempt to call [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) or [System.Management.Automation.Cmdlet.WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError) from another thread.</span></span> <span data-ttu-id="d1f9c-117">Вместо этого ошибки должны быть переданы обратно в основной поток.</span><span class="sxs-lookup"><span data-stu-id="d1f9c-117">Instead, errors must be communicated back to the main thread.</span></span>

<span data-ttu-id="d1f9c-118">Командлет может вызвать исключение в реализации метода [System. Management. Automation. командлет. BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing), [System. Management. Automation. командлет. ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord)или [System. Management. Automation. командлет. EndProcessing](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) .</span><span class="sxs-lookup"><span data-stu-id="d1f9c-118">It is possible for a cmdlet to throw an exception in its implementation of the [System.Management.Automation.Cmdlet.BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing), [System.Management.Automation.Cmdlet.ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord), or [System.Management.Automation.Cmdlet.EndProcessing](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) method.</span></span> <span data-ttu-id="d1f9c-119">Любое исключение, вызванное этими методами (за исключением нескольких серьезных ошибок, которые останавливают узел Windows PowerShell), интерпретируется как завершающая ошибка, которая останавливает конвейер, но не Windows PowerShell в целом.</span><span class="sxs-lookup"><span data-stu-id="d1f9c-119">Any exception thrown from these methods (except for a few severe error conditions that stop the Windows PowerShell host) is interpreted as a terminating error which stops the pipeline, but not Windows PowerShell as a whole.</span></span> <span data-ttu-id="d1f9c-120">(Это относится только к основному потоку командлета.</span><span class="sxs-lookup"><span data-stu-id="d1f9c-120">(This applies only to the main cmdlet thread.</span></span> <span data-ttu-id="d1f9c-121">Неперехваченные исключения в потоках, порожденных командлетом, в общем случае, приостановка работы узла Windows PowerShell.) Рекомендуется использовать [System. Management. Automation. командлет. ThrowTerminatingError \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) вместо создания исключения, поскольку запись об ошибке предоставляет дополнительные сведения о состоянии ошибки, что полезно для конечного пользователя.</span><span class="sxs-lookup"><span data-stu-id="d1f9c-121">Uncaught exceptions in threads spawned by the cmdlet, in general, halt the Windows PowerShell host.) We recommend that you use [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) rather than throwing an exception because the error record provides additional information about the error condition, which is useful to the end-user.</span></span> <span data-ttu-id="d1f9c-122">Командлеты должны учитывать рекомендации управляемого кода для перехвата и обработки всех исключений ( `catch (Exception e)` ).</span><span class="sxs-lookup"><span data-stu-id="d1f9c-122">Cmdlets should honor the managed code guideline against catching and handling all exceptions (`catch (Exception e)`).</span></span> <span data-ttu-id="d1f9c-123">Преобразование исключений известных и ожидаемых типов в записи об ошибках.</span><span class="sxs-lookup"><span data-stu-id="d1f9c-123">Convert only exceptions of known and expected types into error records.</span></span>

## <a name="see-also"></a><span data-ttu-id="d1f9c-124">См. также:</span><span class="sxs-lookup"><span data-stu-id="d1f9c-124">See Also</span></span>

[<span data-ttu-id="d1f9c-125">System. Management. Automation. командлет. BeginProcessing</span><span class="sxs-lookup"><span data-stu-id="d1f9c-125">System.Management.Automation.Cmdlet.BeginProcessing</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing)

[<span data-ttu-id="d1f9c-126">System. Management. Automation. командлет. EndProcessing</span><span class="sxs-lookup"><span data-stu-id="d1f9c-126">System.Management.Automation.Cmdlet.EndProcessing</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing)

[<span data-ttu-id="d1f9c-127">System. Management. Automation. командлет. ProcessRecord</span><span class="sxs-lookup"><span data-stu-id="d1f9c-127">System.Management.Automation.Cmdlet.ProcessRecord</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord)

[<span data-ttu-id="d1f9c-128">System. Management. Automation. Пипелинестоппедексцептион</span><span class="sxs-lookup"><span data-stu-id="d1f9c-128">System.Management.Automation.Pipelinestoppedexception</span></span>](/dotnet/api/System.Management.Automation.PipelineStoppedException)

[<span data-ttu-id="d1f9c-129">System. Management. Automation. командлет. ThrowTerminatingError \*</span><span class="sxs-lookup"><span data-stu-id="d1f9c-129">System.Management.Automation.Cmdlet.Throwterminatingerror\*</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError)

[<span data-ttu-id="d1f9c-130">System. Management. Automation. командлет. WriteError</span><span class="sxs-lookup"><span data-stu-id="d1f9c-130">System.Management.Automation.Cmdlet.WriteError</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.WriteError)

[<span data-ttu-id="d1f9c-131">Записи об ошибках Windows PowerShell</span><span class="sxs-lookup"><span data-stu-id="d1f9c-131">Windows PowerShell Error Records</span></span>](./windows-powershell-error-records.md)

[<span data-ttu-id="d1f9c-132">Запись командлета Windows PowerShell</span><span class="sxs-lookup"><span data-stu-id="d1f9c-132">Writing a Windows PowerShell Cmdlet</span></span>](./writing-a-windows-powershell-cmdlet.md)
